Kakao o auth2.0
depromeet/dgdg-backend pull request #10
Opened 2021-09-28 04:03 UTC by cokkum113

springSecurity가아닌 카카오API로 했습니다.

2021-09-28 04:06 UTC, cokkum113 commented
토큰을 이제 합치는 건가요...?? 
질문이 조금 많습니당... ㅜㅜㅜ😭😭😭

![image](https://user-images.githubusercontent.com/84273370/135021465-68edb3a9-a102-4f7e-bcae-ad500256826c.png)

이 부분에서  localhost:8080/.../config/auth 이렇게 쓰여야 할 거 같은데, 
이런식처럼 써져야만 할 거 같은데 이렇게쓰는 게 맞는지, 

![image](https://user-images.githubusercontent.com/84273370/135021608-9ff3fd70-cf1b-4968-bbc3-b6ab22db0c14.png)

팀원 초대는 이 방식이 맞을까요...??? 남겨주신 이메일 쓰는 란이 여기다 하는게 맞겠죠???

2021-09-28 05:20 UTC, seungh0 requested changes
수고하셨습니다~~

> 토큰을 이제 합치는 건가요...??
> 질문이 조금 많습니당... ㅜㅜㅜ😭😭😭

카카오 인증 API 호출시, 토큰을 생성해서 응답하는 로직? 구현이 필요합니다!

2021-09-28 05:20 UTC, seungh0 commented on dgdg-domain/src/main/java/com/depromeet/dgdg/domain/config/auth/KakaoService.java
> +            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
어... 되게 Low하게... 짜셨군요..! ㅠㅠㅠㅠㅠㅠ

Spring 에서는

WebClient (RestTemplate은 Deprecated 되었습니당..)
- https://www.baeldung.com/spring-5-webclient

FeignClient
- https://spring.io/projects/spring-cloud-openfeign

이런 API Client(APi를 호출하는) 라이브러리 들을 사용하면 쉽게 구현하실 수 있습니당!
(+ 유지보수 수월, 협업 수월 등 많은 이점으로 인해 보통 라이브러리를 사용하는 것 같습니다! (개인적인 생각))

2021-09-28 05:20 UTC, seungh0 commented on dgdg-domain/src/main/resources/templates/application-oauth.yml
> +            user_name_attribute: id
이 정보들 특히 client_id 는 시크릿 정보여서
깃에 올라오면 안됩니당~~ .gitignore 처리 해야되용!

2021-09-28 05:20 UTC, seungh0 commented on dgdg-domain/src/main/java/com/depromeet/dgdg/domain/config/auth/KaKaoController.java
> +    private KakaoService kakaoService;
스프링에서 빈 주입하는 방법이

- 생성자를 이용한 방법
- Setter를 이용한 방법
- Autowired를 이용한 방법

세 가지가 있는데, 가장 선호되는 방법은 "생성자를 이용한 방법"입니다. 
(그래서 자바에서 롬복을 적용하고 @RequiredArgument~ 그 어노테이션을 붙여서 생성자 주입이 되게끔 하는 거죠!)

(뭐 이유는.. final 사용 가능하고(깜빡하고 의존성을 Setter 안하면 에러 뜨는 현상 X), 의존성들 보기 편하고..  등등등등

이유가 있습니다.
(cf 스프링에서 테스트 코드가 아닌 메인 환겨에서 Autowird를 통해 주입하면 Warning 주는 것으로 알고 있습니다..!)

2021-09-28 05:20 UTC, seungh0 commented on build.gradle
> +        implementation ("org.springframework.boot:spring-boot-starter-security")
시큐리티 관련 로직이 없는거 같은데  따로 추가하신 이유가 있을까요..?

2021-09-28 05:20 UTC, seungh0 commented on dgdg-domain/src/main/java/com/depromeet/dgdg/domain/config/auth/KaKaoController.java
> +        System.out.println("#########" + code);
+ 요런 테스트?를 위한 sout()은 깃에 올리기 전에 지우는 것이 좋아요~

(로깅의 목적이시라면  https://programmer93.tistory.com/64 다음을 참고해보시면 좋을거 같습니다~)

2021-09-30 16:47 UTC, seungh0 approved these changes
오오 수고하셨습니다~~
API Client 라이브러리 사용해주셔서 카카오 API 연동쪽 잘 구현해주셨네요~  👍👍

감사합니다~!!!!

2021-09-30 16:47 UTC, seungh0 commented on dgdg-api/src/main/java/com/depromeet/dgdg/config/auth/OAuth2Kakao.java
> +    private final String redirectUrl = "http://dgdg-backend-alb-1085144894.ap-northeast-2.elb.amazonaws.com";
요런 환경에 달라지는 설정 정보들은 프로퍼티로 빼는 것이 좋아 보입니당!
(clientId, redirectUri, grantType, url)

2021-09-30 16:47 UTC, seungh0 commented on dgdg-api/src/main/java/com/depromeet/dgdg/config/auth/UserController.java
> +        userService.oAuth2AuthorizationKakao(code);
이제 여기에 회원가입/로그인 한 유저로 생성한 토큰을 반환하는? 로직이 들어갈까요?~

cf) 그냥 참고로... API 응답에서는 void 반환보다 `BaseResponse.OK` 를 반환하는 것이 좋습니당!

2021-09-30 16:47 UTC, seungh0 commented on dgdg-api/src/main/java/com/depromeet/dgdg/config/auth/UserService.java
> +    public void oAuth2AuthorizationKakao(String code) throws JsonProcessingException {
`throws JsonProcessingException`

계속 throws 하지 않고, 적절한 곳에서 catch 해서 저희만의 Custom Exception으로 변환하면 좋을거 같습니다!

2021-09-30 16:47 UTC, seungh0 commented on dgdg-api/src/main/java/com/depromeet/dgdg/config/auth/OAuth2Kakao.java
> +            throw new UnsupportedOperationException();
저는 
`ex.printStackTrace();`
요거 보다 

` throw new UnsupportedOperationException("이곳에 적절한 메시지");`
Exception에 적절한 메시지를 전달하는 편이긴 합니다!

2021-09-30 16:47 UTC, seungh0 commented on .gitignore
> +java/com/depromeet/dgdg/config/auth/OAuth2Kakao.java
요거 존재하는 파일인가요?

.java 파일을 .gitignore 넣으면 빌드가 안될수도 있어서 환경 변수는 프로퍼티로 빼고 (application.yml)
.gitignore 처리하는 편이 좋을거 같습니다~

2021-09-30 16:47 UTC, seungh0 commented on dgdg-api/src/main/java/com/depromeet/dgdg/config/auth/AuthorizationKakao.java
> +    private String access_token;
취향 차이일수도 있을거 같은데..... (아닌가..)

`    private String access_token;` 보다

자바 컨벤션인 그... 카멜 케이스?? 였나... 를 위해서

```java
@JsonProperty("access_token")
private String accessToken;
```

혹은 클래스에
![image](https://user-images.githubusercontent.com/48153675/135495454-19bd4c19-9249-4976-a8d2-204b645b266e.png)

요런식으로 적용해서 자바에서는 카멜케이스를 유지하되, Json에서는 스네이크를 유지하는 것도 좋아보여요~

2021-09-30 16:47 UTC, seungh0 commented on dgdg-api/src/main/java/com/depromeet/dgdg/config/auth/RestTemplateConfig.java
> +public class RestTemplateConfig {
@emiling @cokkum113 
스프링쪽에서 RestTemplate Deprecated 시키고 Webflux의 WebClient 쓰는 것을 권장하는 것으로 알고 있는데..

일단 카카오 API는 RestTemplate으로 가고, 차후 변경하는 것은 어떨까요?

2021-09-30 16:47 UTC, seungh0 commented on build.gradle
> +        implementation ('org.springframework.boot:spring-boot-starter-oauth2-client')
RestTemplate으로 카카오 API 호출해서 구현해주신 거 같은데.. 요거... 쓰이는 라이브러리인가요? 
(스프링 시큐리티 OAuth2 같은데....  하나도 몰라서.....)

2021-09-30 16:47 UTC, seungh0 commented on dgdg-api/src/main/java/com/depromeet/dgdg/config/auth/OAuth2Kakao.java
> +            return authorization;
` return objectMapper.readValue(response.getBody(), AuthorizationKakao.class);`
해도 좋을거 같아요~

2021-09-30 16:48 UTC, cokkum113 commented
> 오오 수고하셨습니다~~ API Client 라이브러리 사용해주셔서 카카오 API 연동쪽 잘 구현해주셨네요~ 👍👍
 감사합니다!!!

2021-10-01 14:14 UTC, emiling commented on dgdg-api/src/main/java/com/depromeet/dgdg/config/auth/RestTemplateConfig.java
> +public class RestTemplateConfig {
> 일단 카카오 API는 RestTemplate으로 가고, 차후 변경하는 것은 어떨까요?

넵 좋습니다 :) 일단 기능 구현을 우선으로 두고 추후 리팩토링 하는 방향으로 진행하면 좋을 듯 해요!

2021-10-01 14:29 UTC, emiling commented on .gitignore
> +application.yml
혹시 `.gitignore` 에 `application.yml` 파일이 들어가 이유가 있을까요? 😃

`.gitignore` 가 포함된 디렉터리에 `application.yml` 이 존재하지 않고 
다른 `application-jwt`, `application-db` 등을 `include` 하기 위해 `application.yml` 이 필요해서
해당 파일을 제거하는 게 좋을 것 같습니다.

2021-10-01 14:29 UTC, emiling commented on dgdg-api/src/main/resources/templates/application-oauth.yml
> +            client-id: bb5871572c05dfc2a864ede8d7c16246
슬슬 이런 민감한 정보들 어떻게 관리해야할지에 대해 얘기가 필요한 시점이 온 것 같습니다 😊

저번에 말한 AWS Secret Manager 로 관리하면 좋을 듯 한데 
토요일날 좀 더 이야기 나누고 칸반보드에 태스트 추가하면 어떨까요?

2021-10-01 14:35 UTC, emiling approved these changes
크으으 👍🏻   코드 작성해주신 혜수님, 그리고 리뷰 꼼꼼히 해주신 승호님 모두 고생 많으셨습니다 😊

댓글에서도 언급했듯 `RestTemplate` 으로 일단 구현하고 API Client로 리팩토링 하면 좋을 듯 합니다.

2021-10-02 04:19 UTC, seungh0 commented on dgdg-api/src/main/resources/templates/application-oauth.yml
> +            client-id: bb5871572c05dfc2a864ede8d7c16246
좋습니다~

2021-10-02 06:52 UTC, merged